apiVersion: v1
kind: ConfigMap
metadata:
  name: clusters-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: clusters
data:
  XATA_CLUSTERS_NAMESPACE: {{ .Values.config.clusters.clustersNamespace | quote }}
  XATA_CLUSTERS_STORAGE_CLASS: {{ .Values.config.clusters.storageClass | quote }}
  {{- if .Values.config.clusters.nodeSelector }}
  XATA_CLUSTERS_NODE_SELECTOR: {{ .Values.config.clusters.nodeSelector | quote }}
  {{- end }}
  {{- if .Values.config.clusters.volumeSnapshotClass }}
  XATA_CLUSTERS_VOLUME_SNAPSHOT_CLASS: {{ .Values.config.clusters.volumeSnapshotClass | quote }}
  {{- end }}
  {{- if .Values.config.observability.victoriaMetricsURL }}
  VICTORIAMETRICS_URL: {{ .Values.config.observability.victoriaMetricsURL | quote }}
  {{- end }}
  {{- if .Values.config.observability.victoriaLogsURL }}
  VICTORIALOGS_URL: {{ .Values.config.observability.victoriaLogsURL | quote }}
  {{- end }}
  XATA_XATASTOR_ENABLED: {{ .Values.config.clusters.xatastor.enabled | default false | quote }}
  XATA_CLOUD_PROVIDER: {{ .Values.config.clusters.cloudProvider | quote }}
  XATA_USE_STORAGE_QOS_CLASSES: {{ .Values.config.clusters.useStorageQoSClasses | default false | quote }}
  XATA_PGBACKREST_ENCRYPTION_ENABLED: {{ .Values.config.clusters.pgbackrest.encryptionEnabled | default false | quote }}
  {{- if .Values.config.clusters.pgbackrest }}
  {{- if .Values.config.clusters.pgbackrest.bucket }}
  XATA_PGBACKREST_BUCKET: {{ .Values.config.clusters.pgbackrest.bucket | quote }}
  {{- end }}
  {{- if .Values.config.clusters.pgbackrest.region }}
  XATA_BACKUPS_REGION: {{ .Values.config.clusters.pgbackrest.region | quote }}
  {{- end }}
  {{- if .Values.config.clusters.pgbackrest.endpoint }}
  XATA_PGBACKREST_ENDPOINT: {{ .Values.config.clusters.pgbackrest.endpoint | quote }}
  {{- end }}
  {{- if .Values.config.clusters.pgbackrest.gcsServiceAccount }}
  XATA_PGBACKREST_GCS_SERVICE_ACCOUNT: {{ .Values.config.clusters.pgbackrest.gcsServiceAccount | quote }}
  {{- end }}
  {{- if .Values.config.clusters.pgbackrest.azureStorageAccount }}
  XATA_PGBACKREST_AZURE_STORAGE_ACCOUNT: {{ .Values.config.clusters.pgbackrest.azureStorageAccount | quote }}
  {{- end }}
  {{- if .Values.config.clusters.pgbackrest.azureContainer }}
  XATA_PGBACKREST_AZURE_CONTAINER: {{ .Values.config.clusters.pgbackrest.azureContainer | quote }}
  {{- end }}
  {{- if .Values.config.clusters.pgbackrest.credentialsSecret }}
  XATA_PGBACKREST_CREDENTIALS_SECRET: {{ .Values.config.clusters.pgbackrest.credentialsSecret | quote }}
  {{- end }}
  {{- end }}
  {{- with .Values.extraConfig }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
