// Package spec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package spec

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

const (
	XataScopes = "xata.Scopes"
)

// Defines values for BranchCreationDetailsMode.
const (
	BranchCreationDetailsModeCustom  BranchCreationDetailsMode = "custom"
	BranchCreationDetailsModeInherit BranchCreationDetailsMode = "inherit"
)

// Defines values for BranchFromConfigurationMode.
const (
	BranchFromConfigurationModeCustom BranchFromConfigurationMode = "custom"
)

// Defines values for BranchFromParentMode.
const (
	Inherit BranchFromParentMode = "inherit"
)

// Defines values for BranchMetricsRequestAggregations.
const (
	BranchMetricsRequestAggregationsAvg BranchMetricsRequestAggregations = "avg"
	BranchMetricsRequestAggregationsMax BranchMetricsRequestAggregations = "max"
	BranchMetricsRequestAggregationsMin BranchMetricsRequestAggregations = "min"
)

// Defines values for BranchMetricsRequestMetric.
const (
	ConnectionsActive  BranchMetricsRequestMetric = "connections_active"
	ConnectionsIdle    BranchMetricsRequestMetric = "connections_idle"
	Cpu                BranchMetricsRequestMetric = "cpu"
	Disk               BranchMetricsRequestMetric = "disk"
	IopsRead           BranchMetricsRequestMetric = "iops_read"
	IopsWrite          BranchMetricsRequestMetric = "iops_write"
	LatencyRead        BranchMetricsRequestMetric = "latency_read"
	LatencyWrite       BranchMetricsRequestMetric = "latency_write"
	Memory             BranchMetricsRequestMetric = "memory"
	NetworkEgress      BranchMetricsRequestMetric = "network_egress"
	NetworkIngress     BranchMetricsRequestMetric = "network_ingress"
	ReplicationLagTime BranchMetricsRequestMetric = "replication_lag_time"
	ThroughputRead     BranchMetricsRequestMetric = "throughput_read"
	ThroughputWrite    BranchMetricsRequestMetric = "throughput_write"
	WalSyncTime        BranchMetricsRequestMetric = "wal_sync_time"
)

// Defines values for ExtensionType.
const (
	ExtensionTypeExtension ExtensionType = "extension"
	ExtensionTypeModule    ExtensionType = "module"
	ExtensionTypePlugin    ExtensionType = "plugin"
)

// Defines values for MetricSeriesAggregation.
const (
	MetricSeriesAggregationAvg MetricSeriesAggregation = "avg"
	MetricSeriesAggregationMax MetricSeriesAggregation = "max"
	MetricSeriesAggregationMin MetricSeriesAggregation = "min"
)

// Defines values for PostgresConfigParameterDefaultValueSource.
const (
	InstanceType PostgresConfigParameterDefaultValueSource = "instance_type"
	Postgres     PostgresConfigParameterDefaultValueSource = "postgres"
)

// Defines values for PostgresConfigParameterType.
const (
	Boolean  PostgresConfigParameterType = "boolean"
	Bytes    PostgresConfigParameterType = "bytes"
	Duration PostgresConfigParameterType = "duration"
	Enum     PostgresConfigParameterType = "enum"
	Float    PostgresConfigParameterType = "float"
	Int      PostgresConfigParameterType = "int"
	String   PostgresConfigParameterType = "string"
)

// BackupConfiguration Details about the branch continuous backup configuration
type BackupConfiguration struct {
	// BackupTime time of day/week when we are taking a full backup
	BackupTime *string `json:"backupTime,omitempty"`

	// RetentionPeriod how long are we keeping the backups around for
	RetentionPeriod *int32 `json:"retentionPeriod,omitempty"`
}

// BackupMetadata metadata about a continuous backup
type BackupMetadata struct {
	// BranchID the branchID the branch associated with the backup
	BranchID string `json:"branchID"`

	// Description description of the backup
	Description string `json:"description"`

	// EarliestRestore the earlies point in time available for restoring the branch
	EarliestRestore *time.Time `json:"earliestRestore,omitempty"`

	// Id unique identifier for the backup
	Id string `json:"id"`

	// LatestRestore the latest point in time available for restoring the branch
	LatestRestore *time.Time `json:"latestRestore,omitempty"`
}

// BranchCreationDetails Details required when creating a new branch
type BranchCreationDetails struct {
	// BackupConfiguration Details about the branch continuous backup configuration
	BackupConfiguration *BackupConfiguration `json:"backupConfiguration,omitempty"`

	// Description Optional description for the branch purpose or contents (max 50 characters)
	Description *string `json:"description,omitempty"`

	// Mode The mode used to discriminate between types of branches.
	Mode BranchCreationDetailsMode `json:"mode"`

	// Name Human-readable name for the new branch
	Name string `json:"name"`

	// ScaleToZero Configuration for scaling branches to zero when not in use
	ScaleToZero *ScaleToZeroConfiguration `json:"scaleToZero,omitempty"`
	union       json.RawMessage
}

// BranchCreationDetailsMode The mode used to discriminate between types of branches.
type BranchCreationDetailsMode string

// BranchCredentials Credentials for accessing a branch, username and password
type BranchCredentials struct {
	// Password Password for accessing the branch database
	Password string `json:"password"`

	// Username Username for accessing the branch database
	Username string `json:"username"`
}

// BranchFromConfiguration defines model for BranchFromConfiguration.
type BranchFromConfiguration struct {
	// Configuration Configuration details for a database cluster backing a branch
	Configuration ClusterConfiguration        `json:"configuration"`
	Mode          BranchFromConfigurationMode `json:"mode"`
}

// BranchFromConfigurationMode defines model for BranchFromConfiguration.Mode.
type BranchFromConfigurationMode string

// BranchFromParent defines model for BranchFromParent.
type BranchFromParent struct {
	Mode BranchFromParentMode `json:"mode"`

	// ParentID If present, the branch will inherit the parent branch configuration and data
	ParentID string `json:"parentID"`
}

// BranchFromParentMode defines model for BranchFromParent.Mode.
type BranchFromParentMode string

// BranchListMetadata Metadata about a branch used when listing branches in a project
type BranchListMetadata struct {
	// BackupsEnabled Whether the branch is in a region that supports backups
	BackupsEnabled bool `json:"backupsEnabled"`

	// CreatedAt Timestamp when the branch was created
	CreatedAt time.Time `json:"createdAt"`

	// Description Optional description of the branch purpose or contents
	Description *string `json:"description,omitempty"`

	// Id Unique identifier for the branch
	Id string `json:"id"`

	// Name Human-readable name of the branch
	Name string `json:"name"`

	// ParentID Identifier of the parent branch if this is a derived branch, null otherwise
	ParentID *string `json:"parentID"`

	// PublicAccess Whether the branch allows public access without authentication
	PublicAccess bool `json:"publicAccess"`

	// Region Geographic region where the branch is deployed
	Region string `json:"region"`

	// UpdatedAt Timestamp when the branch was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// BranchMetadata Detailed metadata about a branch, including its status and configuration
type BranchMetadata struct {
	// BackupConfiguration Details about the branch continuous backup configuration
	BackupConfiguration *BackupConfiguration `json:"backupConfiguration,omitempty"`

	// BackupsEnabled Whether the branch is in a region that supports backups
	BackupsEnabled bool `json:"backupsEnabled"`

	// Configuration Configuration details for a database cluster backing a branch
	Configuration ClusterConfiguration `json:"configuration"`

	// ConnectionString Database connection string for accessing this branch
	ConnectionString *string `json:"connectionString"`

	// CreatedAt Timestamp when the branch was created
	CreatedAt time.Time `json:"createdAt"`

	// Description Optional description of the branch purpose or contents
	Description *string `json:"description,omitempty"`

	// Id Unique identifier for the branch
	Id string `json:"id"`

	// Name Human-readable name of the branch
	Name string `json:"name"`

	// ParentID Identifier of the parent branch if this is a derived branch, null otherwise
	ParentID *string `json:"parentID"`

	// PublicAccess Whether the branch allows public access without authentication
	PublicAccess bool `json:"publicAccess"`

	// Region Geographic region where the branch is deployed
	Region string `json:"region"`

	// ScaleToZero Configuration for scaling branches to zero when not in use
	ScaleToZero ScaleToZeroConfiguration `json:"scaleToZero"`

	// Status Detailed status information about a branch and its underlying database cluster
	Status BranchStatus `json:"status"`

	// UpdatedAt Timestamp when the branch was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// BranchMetrics A collection of metrics (cpu, memory, disk,...) for each of the instances of a branch
type BranchMetrics struct {
	End    time.Time      `json:"end"`
	Metric string         `json:"metric"`
	Series []MetricSeries `json:"series"`
	Start  time.Time      `json:"start"`

	// Unit The unit of the metric (percentage, bytes, ms, etc.)
	Unit string `json:"unit"`
}

// BranchMetricsRequest defines model for BranchMetricsRequest.
type BranchMetricsRequest struct {
	// Aggregations List of aggregations to get, this is how the data-points within the interval are aggregated. Each one will generate a separate time-series in the response.
	Aggregations []BranchMetricsRequestAggregations `json:"aggregations"`

	// End End time
	End time.Time `json:"end"`

	// Instances List of instance IDs to query
	Instances []string `json:"instances"`

	// Metric Metric name to query
	Metric BranchMetricsRequestMetric `json:"metric"`

	// Start Start time
	Start time.Time `json:"start"`
}

// BranchMetricsRequestAggregations defines model for BranchMetricsRequest.Aggregations.
type BranchMetricsRequestAggregations string

// BranchMetricsRequestMetric Metric name to query
type BranchMetricsRequestMetric string

// BranchShortMetadata Basic metadata about a branch, used in response to create/update operations
type BranchShortMetadata struct {
	// ConnectionString Database connection string for accessing this branch
	ConnectionString *string `json:"connectionString"`

	// CreatedAt Timestamp when the branch was created
	CreatedAt time.Time `json:"createdAt"`

	// Description Optional description of the branch purpose or contents
	Description *string `json:"description,omitempty"`

	// Id Unique identifier for the branch
	Id string `json:"id"`

	// Name Human-readable name of the branch
	Name string `json:"name"`

	// ParentID Identifier of the parent branch if this is a derived branch, null otherwise
	ParentID *string `json:"parentID"`

	// PublicAccess Whether the branch allows public access without authentication
	PublicAccess bool `json:"publicAccess"`

	// Region Geographic region where the branch is deployed
	Region string `json:"region"`

	// UpdatedAt Timestamp when the branch was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// BranchStatus Detailed status information about a branch and its underlying database cluster
type BranchStatus struct {
	// InstanceCount Total number of database instances in the cluster
	InstanceCount int `json:"instanceCount"`

	// InstanceReadyCount Number of database instances that are ready and operational
	InstanceReadyCount int `json:"instanceReadyCount"`

	// Instances Details about each individual database instance in the cluster
	Instances []InstanceStatus `json:"instances"`

	// Lifecycle Information about the current lifecycle state of a database cluster
	// Deprecated:
	Lifecycle *ClusterLifecycle `json:"lifecycle,omitempty"`

	// Message Human-readable message explaining the current status
	// Deprecated:
	Message *string `json:"message,omitempty"`

	// Status Status indicator for the branch according to CNPG
	Status string `json:"status"`

	// StatusType Type of status of the branch
	StatusType interface{} `json:"statusType"`
}

// BranchUpdateDetails Details that can be updated for an existing branch
type BranchUpdateDetails struct {
	// BackupConfiguration Details about the branch continuous backup configuration
	BackupConfiguration *BackupConfiguration `json:"backupConfiguration,omitempty"`

	// Description New description for the branch (max 50 characters)
	Description *string `json:"description,omitempty"`

	// Hibernate Enabled when the branch should be hibernated, disabled if it needs to be reactivated.
	Hibernate *bool `json:"hibernate,omitempty"`

	// Image PostgreSQL image to use for the database instances
	Image *string `json:"image,omitempty"`

	// InstanceType New instance type for the branch
	InstanceType *string `json:"instanceType,omitempty"`

	// Name New name for the branch
	Name *string `json:"name,omitempty"`

	// PostgresConfigurationParameters Arbitrary PostgreSQL configuration parameters for the cluster
	PostgresConfigurationParameters *map[string]string `json:"postgresConfigurationParameters,omitempty"`

	// PreloadLibraries List of PostgreSQL extensions and libraries to preload
	PreloadLibraries *[]string `json:"preloadLibraries,omitempty"`

	// Replicas Number of database replicas to scale to
	Replicas *int32 `json:"replicas,omitempty"`

	// ScaleToZero Configuration for scaling branches to zero when not in use
	ScaleToZero *ScaleToZeroConfiguration `json:"scaleToZero,omitempty"`

	// Storage Branch storage in GiB (gigabytes)
	Storage *int32 `json:"storage,omitempty"`
}

// CidrEntry defines model for CidrEntry.
type CidrEntry struct {
	// Cidr CIDR block (e.g., "192.168.0.0/24")
	Cidr string `json:"cidr"`

	// Description Optional label for the CIDR entry
	Description *string `json:"description,omitempty"`
}

// ClusterConfiguration Configuration details for a database cluster backing a branch
type ClusterConfiguration struct {
	// Image PostgreSQL image to use for the database instances
	Image string `json:"image"`

	// InstanceType The instance type according to the xata instance types available
	InstanceType string `json:"instanceType"`

	// PostgresConfigurationParameters Arbitrary PostgreSQL configuration parameters for the cluster
	PostgresConfigurationParameters *map[string]string `json:"postgresConfigurationParameters,omitempty"`

	// PreloadLibraries List of PostgreSQL extensions and libraries to preload
	PreloadLibraries *[]string `json:"preloadLibraries,omitempty"`

	// Region Geographic region where the cluster will be deployed
	Region string `json:"region"`

	// Replicas Number of replicas in the branch. Every child branch is created with no replicas. This can be updated.
	Replicas int32 `json:"replicas"`

	// Storage Branch storage in GiB (gigabytes)
	Storage *int32 `json:"storage,omitempty"`
}

// ClusterLifecycle Information about the current lifecycle state of a database cluster
type ClusterLifecycle struct {
	// Phase Current phase within the lifecycle process
	Phase string `json:"phase"`

	// Reason Reason for the current lifecycle state, especially useful for non-ready states
	Reason *string `json:"reason,omitempty"`

	// State Current operational state of the cluster (ready, creating, updating, etc.)
	State interface{} `json:"state"`
}

// CreateGithubAppInstallationRequest defines model for CreateGithubAppInstallationRequest.
type CreateGithubAppInstallationRequest struct {
	// InstallationId GitHub App installation ID
	InstallationId int64 `json:"installationId"`
}

// CreateGithubRepositoryRequest defines model for CreateGithubRepositoryRequest.
type CreateGithubRepositoryRequest struct {
	// GithubRepositoryID GitHub repository ID
	GithubRepositoryID int64 `json:"githubRepositoryID"`
}

// Extension Details of a postgres extension
type Extension struct {
	// Description Extension description
	Description string `json:"description"`

	// Docs Documentation URL
	Docs string `json:"docs"`

	// Name Extension name
	Name string `json:"name"`

	// PreloadRequired is preload required for the extension or not
	PreloadRequired bool `json:"preloadRequired"`

	// Type type of installation
	Type ExtensionType `json:"type"`

	// Version Extension version
	Version string `json:"version"`
}

// ExtensionType type of installation
type ExtensionType string

// GithubInstallation A GitHub App installation associated with an organization
type GithubInstallation struct {
	// CreatedAt Timestamp when the installation was created
	CreatedAt time.Time `json:"createdAt"`

	// Id Unique identifier of the installation record
	Id string `json:"id"`

	// InstallationId GitHub App installation ID
	InstallationId int64 `json:"installationId"`

	// Organization Organization ID this installation belongs to
	Organization string `json:"organization"`

	// UpdatedAt Timestamp when the installation was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// GithubRepository A mapping between a GitHub repository and a Xata project
type GithubRepository struct {
	// CreatedAt Timestamp when the mapping was created
	CreatedAt time.Time `json:"createdAt"`

	// GithubRepositoryID GitHub repository ID
	GithubRepositoryID int64 `json:"githubRepositoryID"`

	// Id Unique identifier of the mapping record
	Id string `json:"id"`

	// Project Project ID this mapping is associated with
	Project string `json:"project"`

	// RootBranchId ID of the root Xata branch mapped to this repository
	RootBranchId string `json:"rootBranchId"`

	// UpdatedAt Timestamp when the mapping was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// IPFilteringConfiguration Configuration for IP filtering on project branches
type IPFilteringConfiguration struct {
	Cidr []CidrEntry `json:"cidr"`

	// Enabled Whether IP filtering is enabled
	Enabled bool `json:"enabled"`
}

// Image Details of a postgres image
type Image struct {
	// FullVersion full postgres version
	FullVersion string `json:"fullVersion"`

	// MajorVersion major postgres version
	MajorVersion string `json:"majorVersion"`

	// Name Image name
	Name string `json:"name"`

	// Region region where this instance type is available
	Region *[]string `json:"region,omitempty"`
}

// InstanceStatus Status information about an individual database instance within a cluster
type InstanceStatus struct {
	// Id Unique identifier for the database instance
	Id string `json:"id"`

	// Primary Indicates if this instance is currently the primary (write) instance
	Primary bool `json:"primary"`

	// Status Current operational status of the instance
	Status string `json:"status"`

	// TargetPrimary Indicates if this instance is the target primary during a failover operation
	TargetPrimary bool `json:"targetPrimary"`
}

// MetricSeries The metric series
type MetricSeries struct {
	// Aggregation The aggregation used to generate this time-series
	Aggregation MetricSeriesAggregation `json:"aggregation"`

	// InstanceID ID of the instance
	InstanceID string `json:"instanceID"`
	Values     []struct {
		Timestamp time.Time `json:"timestamp"`
		Value     float32   `json:"value"`
	} `json:"values"`
}

// MetricSeriesAggregation The aggregation used to generate this time-series
type MetricSeriesAggregation string

// OrganizationID defines model for OrganizationID.
type OrganizationID = string

// PostgresConfigDetails Detailed information about PostgreSQL configuration parameters for a branch
type PostgresConfigDetails struct {
	// Parameters Array of PostgreSQL configuration parameters with detailed information
	Parameters []PostgresConfigParameter `json:"parameters"`
}

// PostgresConfigParameter Detailed information about a single PostgreSQL configuration parameter
type PostgresConfigParameter struct {
	// AcceptableRange Information about the acceptable range of values for this parameter
	AcceptableRange *struct {
		// EnumValues List of allowed enum values (if applicable)
		EnumValues *[]string `json:"enumValues,omitempty"`

		// MaxValue Maximum allowed value (if applicable)
		MaxValue *string `json:"maxValue,omitempty"`

		// MinValue Minimum allowed value (if applicable)
		MinValue *string `json:"minValue,omitempty"`
	} `json:"acceptableRange,omitempty"`

	// CurrentValue The current value of this parameter in the branch
	CurrentValue string `json:"currentValue"`

	// DefaultValue The default value for this parameter
	DefaultValue string `json:"defaultValue"`

	// DefaultValueSource The source of the default value
	DefaultValueSource PostgresConfigParameterDefaultValueSource `json:"defaultValueSource"`

	// Description Human-readable description of what the parameter controls
	Description string `json:"description"`

	// DocumentationLink Link to PostgreSQL documentation for this parameter
	DocumentationLink string `json:"documentationLink"`

	// Name The name of the PostgreSQL parameter
	Name string `json:"name"`

	// Recommendation Optional recommendation for this parameter (currently empty)
	Recommendation string `json:"recommendation"`

	// RestartRequired Whether a database restart is required for this parameter change to take effect
	RestartRequired *bool `json:"restartRequired,omitempty"`

	// Section The section/category this parameter belongs to
	Section string `json:"section"`

	// Type The data type of the parameter
	Type PostgresConfigParameterType `json:"type"`
}

// PostgresConfigParameterDefaultValueSource The source of the default value
type PostgresConfigParameterDefaultValueSource string

// PostgresConfigParameterType The data type of the parameter
type PostgresConfigParameterType string

// Project Details of a project including its ID, name, and creation/update timestamps
type Project struct {
	// Configuration Configuration details for a project, including its scale to zero settings
	Configuration ProjectConfiguration `json:"configuration"`

	// CreatedAt Timestamp when the project was created
	CreatedAt time.Time `json:"createdAt"`

	// Id Unique identifier for the project
	Id string `json:"id"`

	// Name Human-readable name of the project
	Name string `json:"name"`

	// UpdatedAt Timestamp when the project was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// ProjectConfiguration Configuration details for a project, including its scale to zero settings
type ProjectConfiguration struct {
	// IpFiltering Configuration for IP filtering on project branches
	IpFiltering *IPFilteringConfiguration `json:"ipFiltering,omitempty"`

	// ScaleToZero Whether the project branches are configured to scale down to zero when not in use
	ScaleToZero ProjectScaleToZeroConfiguration `json:"scaleToZero"`
}

// ProjectLimits Resource limits and constraints for projects within an organization
type ProjectLimits struct {
	// Images List of PostgreSQL image identifiers that can be used for branches
	Images []string `json:"images"`

	// MaxBranches Maximum number of branches allowed per project
	MaxBranches int `json:"maxBranches"`

	// MaxDescriptionLength Maximum character length allowed for project descriptions
	MaxDescriptionLength int `json:"maxDescriptionLength"`

	// MaxInstances Maximum number of database instances allowed per branch
	MaxInstances int `json:"maxInstances"`

	// MinInstances Minimum number of database instances required per branch
	MinInstances int `json:"minInstances"`

	// Regions List of region identifiers where branches can be deployed
	Regions []string `json:"regions"`
}

// ProjectScaleToZeroConfiguration Whether the project branches are configured to scale down to zero when not in use
type ProjectScaleToZeroConfiguration struct {
	// BaseBranches Configuration for scaling branches to zero when not in use
	BaseBranches ScaleToZeroConfiguration `json:"baseBranches"`

	// ChildBranches Configuration for scaling branches to zero when not in use
	ChildBranches ScaleToZeroConfiguration `json:"childBranches"`
}

// RestoreDetails Metadata about a backup, used in request to create a restore. If configuration is not provided, the branch will inherit the source branch configuration.
type RestoreDetails struct {
	// BackupConfiguration Details about the branch continuous backup configuration
	BackupConfiguration *BackupConfiguration `json:"backupConfiguration,omitempty"`

	// Configuration Configuration details for a database cluster backing a branch
	Configuration *ClusterConfiguration `json:"configuration,omitempty"`

	// Description Optional description of the branch purpose or contents
	Description *string `json:"description,omitempty"`

	// Name Human-readable name of the branch
	Name string `json:"name"`

	// ScaleToZero Configuration for scaling branches to zero when not in use
	ScaleToZero *ScaleToZeroConfiguration `json:"scaleToZero,omitempty"`
}

// ScaleToZeroConfiguration Configuration for scaling branches to zero when not in use
type ScaleToZeroConfiguration struct {
	// Enabled Whether scale to zero is enabled
	Enabled bool `json:"enabled"`

	// InactivityPeriodMinutes Duration in minutes after which branches will be hibernated if not accessed
	InactivityPeriodMinutes int `json:"inactivityPeriodMinutes"`
}

// UpdateGithubAppInstallationRequest defines model for UpdateGithubAppInstallationRequest.
type UpdateGithubAppInstallationRequest struct {
	// InstallationId GitHub App installation ID
	InstallationId int64 `json:"installationId"`
}

// UpdateGithubRepositoryRequest defines model for UpdateGithubRepositoryRequest.
type UpdateGithubRepositoryRequest struct {
	// GithubRepositoryID GitHub repository ID
	GithubRepositoryID int64 `json:"githubRepositoryID"`
}

// UpdateProjectConfiguration Partial configuration update for a project
type UpdateProjectConfiguration struct {
	// IpFiltering Configuration for IP filtering on project branches
	IpFiltering *IPFilteringConfiguration `json:"ipFiltering,omitempty"`

	// ScaleToZero Whether the project branches are configured to scale down to zero when not in use
	ScaleToZero *ProjectScaleToZeroConfiguration `json:"scaleToZero,omitempty"`
}

// AuthorizationError defines model for AuthorizationError.
type AuthorizationError struct {
	// Id Error identifier for tracking and debugging
	Id *string `json:"id,omitempty"`

	// Message Human-readable error message explaining the authentication or authorization issue
	Message string `json:"message"`
}

// GenericError defines model for GenericError.
type GenericError struct {
	// Id Error identifier for tracking and debugging
	Id *string `json:"id,omitempty"`

	// Message Human-readable error message explaining the issue
	Message string `json:"message"`
}

// PreconditionFailedError defines model for PreconditionFailedError.
type PreconditionFailedError struct {
	// Id Error identifier for tracking and debugging
	Id *string `json:"id,omitempty"`

	// Message Human-readable error message explaining the precondition failure
	Message string `json:"message"`
}

// ListExtensionsParams defines parameters for ListExtensions.
type ListExtensionsParams struct {
	// Image Image for which we list extensions
	Image string `form:"image" json:"image"`

	// Region Region to list extensions for image in
	Region *string `form:"region,omitempty" json:"region,omitempty"`
}

// ListImagesParams defines parameters for ListImages.
type ListImagesParams struct {
	// Region Region to check image availability for organization
	Region *string `form:"region,omitempty" json:"region,omitempty"`
}

// ListInstanceTypesParams defines parameters for ListInstanceTypes.
type ListInstanceTypesParams struct {
	// Region Region to check instance type availability for
	Region string `form:"region" json:"region"`
}

// CreateProjectJSONBody defines parameters for CreateProject.
type CreateProjectJSONBody struct {
	// Configuration Configuration details for a project, including its scale to zero settings
	Configuration *ProjectConfiguration `json:"configuration,omitempty"`

	// Name Human-readable name for the new project
	Name string `json:"name"`
}

// UpdateProjectJSONBody defines parameters for UpdateProject.
type UpdateProjectJSONBody struct {
	// Configuration Partial configuration update for a project
	Configuration *UpdateProjectConfiguration `json:"configuration,omitempty"`

	// Name New name for the project
	Name *string `json:"name,omitempty"`
}

// GetBranchCredentialsParams defines parameters for GetBranchCredentials.
type GetBranchCredentialsParams struct {
	// Username Username that the credentials requested for
	Username *string `form:"username,omitempty" json:"username,omitempty"`
}

// CreateGithubAppInstallationJSONRequestBody defines body for CreateGithubAppInstallation for application/json ContentType.
type CreateGithubAppInstallationJSONRequestBody = CreateGithubAppInstallationRequest

// UpdateGithubAppInstallationJSONRequestBody defines body for UpdateGithubAppInstallation for application/json ContentType.
type UpdateGithubAppInstallationJSONRequestBody = UpdateGithubAppInstallationRequest

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody CreateProjectJSONBody

// UpdateProjectJSONRequestBody defines body for UpdateProject for application/json ContentType.
type UpdateProjectJSONRequestBody UpdateProjectJSONBody

// CreateBranchJSONRequestBody defines body for CreateBranch for application/json ContentType.
type CreateBranchJSONRequestBody = BranchCreationDetails

// UpdateBranchJSONRequestBody defines body for UpdateBranch for application/json ContentType.
type UpdateBranchJSONRequestBody = BranchUpdateDetails

// CreateGithubRepositoryJSONRequestBody defines body for CreateGithubRepository for application/json ContentType.
type CreateGithubRepositoryJSONRequestBody = CreateGithubRepositoryRequest

// UpdateGithubRepositoryJSONRequestBody defines body for UpdateGithubRepository for application/json ContentType.
type UpdateGithubRepositoryJSONRequestBody = UpdateGithubRepositoryRequest

// BranchMetricsJSONRequestBody defines body for BranchMetrics for application/json ContentType.
type BranchMetricsJSONRequestBody = BranchMetricsRequest

// RestoreFromBackupJSONRequestBody defines body for RestoreFromBackup for application/json ContentType.
type RestoreFromBackupJSONRequestBody = RestoreDetails

// AsBranchFromParent returns the union data inside the BranchCreationDetails as a BranchFromParent
func (t BranchCreationDetails) AsBranchFromParent() (BranchFromParent, error) {
	var body BranchFromParent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBranchFromParent overwrites any union data inside the BranchCreationDetails as the provided BranchFromParent
func (t *BranchCreationDetails) FromBranchFromParent(v BranchFromParent) error {
	t.Mode = "inherit"

	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBranchFromParent performs a merge with any union data inside the BranchCreationDetails, using the provided BranchFromParent
func (t *BranchCreationDetails) MergeBranchFromParent(v BranchFromParent) error {
	t.Mode = "inherit"

	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBranchFromConfiguration returns the union data inside the BranchCreationDetails as a BranchFromConfiguration
func (t BranchCreationDetails) AsBranchFromConfiguration() (BranchFromConfiguration, error) {
	var body BranchFromConfiguration
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBranchFromConfiguration overwrites any union data inside the BranchCreationDetails as the provided BranchFromConfiguration
func (t *BranchCreationDetails) FromBranchFromConfiguration(v BranchFromConfiguration) error {
	t.Mode = "custom"

	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBranchFromConfiguration performs a merge with any union data inside the BranchCreationDetails, using the provided BranchFromConfiguration
func (t *BranchCreationDetails) MergeBranchFromConfiguration(v BranchFromConfiguration) error {
	t.Mode = "custom"

	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t BranchCreationDetails) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"mode"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t BranchCreationDetails) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "custom":
		return t.AsBranchFromConfiguration()
	case "inherit":
		return t.AsBranchFromParent()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t BranchCreationDetails) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.BackupConfiguration != nil {
		object["backupConfiguration"], err = json.Marshal(t.BackupConfiguration)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'backupConfiguration': %w", err)
		}
	}

	if t.Description != nil {
		object["description"], err = json.Marshal(t.Description)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'description': %w", err)
		}
	}

	object["mode"], err = json.Marshal(t.Mode)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'mode': %w", err)
	}

	object["name"], err = json.Marshal(t.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	if t.ScaleToZero != nil {
		object["scaleToZero"], err = json.Marshal(t.ScaleToZero)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'scaleToZero': %w", err)
		}
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *BranchCreationDetails) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["backupConfiguration"]; found {
		err = json.Unmarshal(raw, &t.BackupConfiguration)
		if err != nil {
			return fmt.Errorf("error reading 'backupConfiguration': %w", err)
		}
	}

	if raw, found := object["description"]; found {
		err = json.Unmarshal(raw, &t.Description)
		if err != nil {
			return fmt.Errorf("error reading 'description': %w", err)
		}
	}

	if raw, found := object["mode"]; found {
		err = json.Unmarshal(raw, &t.Mode)
		if err != nil {
			return fmt.Errorf("error reading 'mode': %w", err)
		}
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &t.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
	}

	if raw, found := object["scaleToZero"]; found {
		err = json.Unmarshal(raw, &t.ScaleToZero)
		if err != nil {
			return fmt.Errorf("error reading 'scaleToZero': %w", err)
		}
	}

	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get available extensions for image
	// (GET /organizations/{organizationID}/extensions)
	ListExtensions(ctx echo.Context, organizationID OrganizationID, params ListExtensionsParams) error
	// List GitHub App installations for organization
	// (GET /organizations/{organizationID}/githubapp/installations)
	ListGithubAppInstallations(ctx echo.Context, organizationID OrganizationID) error
	// Create GitHub App installation
	// (POST /organizations/{organizationID}/githubapp/installations)
	CreateGithubAppInstallation(ctx echo.Context, organizationID OrganizationID) error
	// Update GitHub App installation
	// (PUT /organizations/{organizationID}/githubapp/installations/{githubInstallationID})
	UpdateGithubAppInstallation(ctx echo.Context, organizationID OrganizationID, githubInstallationID string) error
	// Get available images
	// (GET /organizations/{organizationID}/images)
	ListImages(ctx echo.Context, organizationID OrganizationID, params ListImagesParams) error
	// Get available instance types
	// (GET /organizations/{organizationID}/instanceTypes)
	ListInstanceTypes(ctx echo.Context, organizationID OrganizationID, params ListInstanceTypesParams) error
	// List all projects
	// (GET /organizations/{organizationID}/projects)
	ListProjects(ctx echo.Context, organizationID OrganizationID) error
	// Create a new project
	// (POST /organizations/{organizationID}/projects)
	CreateProject(ctx echo.Context, organizationID OrganizationID) error
	// Get project resource limits
	// (GET /organizations/{organizationID}/projects/limits)
	GetDefaultProjectLimits(ctx echo.Context, organizationID OrganizationID) error
	// Delete a project
	// (DELETE /organizations/{organizationID}/projects/{projectID})
	DeleteProject(ctx echo.Context, organizationID OrganizationID, projectID string) error
	// Get project details
	// (GET /organizations/{organizationID}/projects/{projectID})
	GetProject(ctx echo.Context, organizationID OrganizationID, projectID string) error
	// Update project details
	// (PATCH /organizations/{organizationID}/projects/{projectID})
	UpdateProject(ctx echo.Context, organizationID OrganizationID, projectID string) error
	// List project backups
	// (GET /organizations/{organizationID}/projects/{projectID}/backups)
	ListBackups(ctx echo.Context, organizationID OrganizationID, projectID string) error
	// Get project backup by ID
	// (GET /organizations/{organizationID}/projects/{projectID}/backups/{backupID})
	GetBackup(ctx echo.Context, organizationID OrganizationID, projectID string, backupID string) error
	// List all branches
	// (GET /organizations/{organizationID}/projects/{projectID}/branches)
	ListBranches(ctx echo.Context, organizationID OrganizationID, projectID string) error
	// Create a new branch
	// (POST /organizations/{organizationID}/projects/{projectID}/branches)
	CreateBranch(ctx echo.Context, organizationID OrganizationID, projectID string) error
	// Delete a branch
	// (DELETE /organizations/{organizationID}/projects/{projectID}/branches/{branchID})
	DeleteBranch(ctx echo.Context, organizationID OrganizationID, projectID string, branchID string) error
	// Get branch details
	// (GET /organizations/{organizationID}/projects/{projectID}/branches/{branchID})
	DescribeBranch(ctx echo.Context, organizationID OrganizationID, projectID string, branchID string) error
	// Update branch details
	// (PATCH /organizations/{organizationID}/projects/{projectID}/branches/{branchID})
	UpdateBranch(ctx echo.Context, organizationID OrganizationID, projectID string, branchID string) error
	// Retrieve branch credentials
	// (GET /organizations/{organizationID}/projects/{projectID}/branches/{branchID}/credentials)
	GetBranchCredentials(ctx echo.Context, organizationID OrganizationID, projectID string, branchID string, params GetBranchCredentialsParams) error
	// Delete GitHub repository mapping
	// (DELETE /organizations/{organizationID}/projects/{projectID}/branches/{branchID}/githubapp/repository)
	DeleteGithubRepository(ctx echo.Context, organizationID OrganizationID, projectID string, branchID string) error
	// Get GitHub repository for branch
	// (GET /organizations/{organizationID}/projects/{projectID}/branches/{branchID}/githubapp/repository)
	GetGithubRepository(ctx echo.Context, organizationID OrganizationID, projectID string, branchID string) error
	// Create GitHub repository mapping
	// (POST /organizations/{organizationID}/projects/{projectID}/branches/{branchID}/githubapp/repository)
	CreateGithubRepository(ctx echo.Context, organizationID OrganizationID, projectID string, branchID string) error
	// Update GitHub repository mapping
	// (PUT /organizations/{organizationID}/projects/{projectID}/branches/{branchID}/githubapp/repository)
	UpdateGithubRepository(ctx echo.Context, organizationID OrganizationID, projectID string, branchID string) error
	// Retrieve branch metrics
	// (POST /organizations/{organizationID}/projects/{projectID}/branches/{branchID}/metrics)
	BranchMetrics(ctx echo.Context, organizationID OrganizationID, projectID string, branchID string) error
	// Get PostgreSQL configuration details
	// (GET /organizations/{organizationID}/projects/{projectID}/branches/{branchID}/postgres-config)
	GetBranchPostgresConfig(ctx echo.Context, organizationID OrganizationID, projectID string, branchID string) error
	// Create a new branch from a backup of another branch
	// (POST /organizations/{organizationID}/projects/{projectID}/branches/{branchID}/restore)
	RestoreFromBackup(ctx echo.Context, organizationID OrganizationID, projectID string, branchID string) error
	// Get available regions
	// (GET /organizations/{organizationID}/regions)
	ListRegions(ctx echo.Context, organizationID OrganizationID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ListExtensions converts echo context to params.
func (w *ServerInterfaceWrapper) ListExtensions(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:read"})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListExtensionsParams
	// ------------- Required query parameter "image" -------------

	err = runtime.BindQueryParameter("form", true, true, "image", ctx.QueryParams(), &params.Image)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter image: %s", err))
	}

	// ------------- Optional query parameter "region" -------------

	err = runtime.BindQueryParameter("form", true, false, "region", ctx.QueryParams(), &params.Region)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter region: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListExtensions(ctx, organizationID, params)
	return err
}

// ListGithubAppInstallations converts echo context to params.
func (w *ServerInterfaceWrapper) ListGithubAppInstallations(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"project:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListGithubAppInstallations(ctx, organizationID)
	return err
}

// CreateGithubAppInstallation converts echo context to params.
func (w *ServerInterfaceWrapper) CreateGithubAppInstallation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateGithubAppInstallation(ctx, organizationID)
	return err
}

// UpdateGithubAppInstallation converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateGithubAppInstallation(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "githubInstallationID" -------------
	var githubInstallationID string

	err = runtime.BindStyledParameterWithOptions("simple", "githubInstallationID", ctx.Param("githubInstallationID"), &githubInstallationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter githubInstallationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateGithubAppInstallation(ctx, organizationID, githubInstallationID)
	return err
}

// ListImages converts echo context to params.
func (w *ServerInterfaceWrapper) ListImages(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:read"})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListImagesParams
	// ------------- Optional query parameter "region" -------------

	err = runtime.BindQueryParameter("form", true, false, "region", ctx.QueryParams(), &params.Region)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter region: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListImages(ctx, organizationID, params)
	return err
}

// ListInstanceTypes converts echo context to params.
func (w *ServerInterfaceWrapper) ListInstanceTypes(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"org:read"})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListInstanceTypesParams
	// ------------- Required query parameter "region" -------------

	err = runtime.BindQueryParameter("form", true, true, "region", ctx.QueryParams(), &params.Region)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter region: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListInstanceTypes(ctx, organizationID, params)
	return err
}

// ListProjects converts echo context to params.
func (w *ServerInterfaceWrapper) ListProjects(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"project:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListProjects(ctx, organizationID)
	return err
}

// CreateProject converts echo context to params.
func (w *ServerInterfaceWrapper) CreateProject(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"project:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateProject(ctx, organizationID)
	return err
}

// GetDefaultProjectLimits converts echo context to params.
func (w *ServerInterfaceWrapper) GetDefaultProjectLimits(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"project:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetDefaultProjectLimits(ctx, organizationID)
	return err
}

// DeleteProject converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteProject(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	ctx.Set(XataScopes, []string{"project:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteProject(ctx, organizationID, projectID)
	return err
}

// GetProject converts echo context to params.
func (w *ServerInterfaceWrapper) GetProject(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	ctx.Set(XataScopes, []string{"project:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetProject(ctx, organizationID, projectID)
	return err
}

// UpdateProject converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateProject(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	ctx.Set(XataScopes, []string{"project:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateProject(ctx, organizationID, projectID)
	return err
}

// ListBackups converts echo context to params.
func (w *ServerInterfaceWrapper) ListBackups(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	ctx.Set(XataScopes, []string{"project:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListBackups(ctx, organizationID, projectID)
	return err
}

// GetBackup converts echo context to params.
func (w *ServerInterfaceWrapper) GetBackup(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	// ------------- Path parameter "backupID" -------------
	var backupID string

	err = runtime.BindStyledParameterWithOptions("simple", "backupID", ctx.Param("backupID"), &backupID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter backupID: %s", err))
	}

	ctx.Set(XataScopes, []string{"project:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBackup(ctx, organizationID, projectID, backupID)
	return err
}

// ListBranches converts echo context to params.
func (w *ServerInterfaceWrapper) ListBranches(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	ctx.Set(XataScopes, []string{"branch:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListBranches(ctx, organizationID, projectID)
	return err
}

// CreateBranch converts echo context to params.
func (w *ServerInterfaceWrapper) CreateBranch(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	ctx.Set(XataScopes, []string{"branch:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateBranch(ctx, organizationID, projectID)
	return err
}

// DeleteBranch converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteBranch(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	// ------------- Path parameter "branchID" -------------
	var branchID string

	err = runtime.BindStyledParameterWithOptions("simple", "branchID", ctx.Param("branchID"), &branchID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter branchID: %s", err))
	}

	ctx.Set(XataScopes, []string{"branch:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteBranch(ctx, organizationID, projectID, branchID)
	return err
}

// DescribeBranch converts echo context to params.
func (w *ServerInterfaceWrapper) DescribeBranch(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	// ------------- Path parameter "branchID" -------------
	var branchID string

	err = runtime.BindStyledParameterWithOptions("simple", "branchID", ctx.Param("branchID"), &branchID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter branchID: %s", err))
	}

	ctx.Set(XataScopes, []string{"branch:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DescribeBranch(ctx, organizationID, projectID, branchID)
	return err
}

// UpdateBranch converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateBranch(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	// ------------- Path parameter "branchID" -------------
	var branchID string

	err = runtime.BindStyledParameterWithOptions("simple", "branchID", ctx.Param("branchID"), &branchID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter branchID: %s", err))
	}

	ctx.Set(XataScopes, []string{"branch:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateBranch(ctx, organizationID, projectID, branchID)
	return err
}

// GetBranchCredentials converts echo context to params.
func (w *ServerInterfaceWrapper) GetBranchCredentials(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	// ------------- Path parameter "branchID" -------------
	var branchID string

	err = runtime.BindStyledParameterWithOptions("simple", "branchID", ctx.Param("branchID"), &branchID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter branchID: %s", err))
	}

	ctx.Set(XataScopes, []string{"credentials:read"})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetBranchCredentialsParams
	// ------------- Optional query parameter "username" -------------

	err = runtime.BindQueryParameter("form", true, false, "username", ctx.QueryParams(), &params.Username)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter username: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBranchCredentials(ctx, organizationID, projectID, branchID, params)
	return err
}

// DeleteGithubRepository converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteGithubRepository(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	// ------------- Path parameter "branchID" -------------
	var branchID string

	err = runtime.BindStyledParameterWithOptions("simple", "branchID", ctx.Param("branchID"), &branchID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter branchID: %s", err))
	}

	ctx.Set(XataScopes, []string{"project:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteGithubRepository(ctx, organizationID, projectID, branchID)
	return err
}

// GetGithubRepository converts echo context to params.
func (w *ServerInterfaceWrapper) GetGithubRepository(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	// ------------- Path parameter "branchID" -------------
	var branchID string

	err = runtime.BindStyledParameterWithOptions("simple", "branchID", ctx.Param("branchID"), &branchID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter branchID: %s", err))
	}

	ctx.Set(XataScopes, []string{"project:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetGithubRepository(ctx, organizationID, projectID, branchID)
	return err
}

// CreateGithubRepository converts echo context to params.
func (w *ServerInterfaceWrapper) CreateGithubRepository(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	// ------------- Path parameter "branchID" -------------
	var branchID string

	err = runtime.BindStyledParameterWithOptions("simple", "branchID", ctx.Param("branchID"), &branchID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter branchID: %s", err))
	}

	ctx.Set(XataScopes, []string{"project:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateGithubRepository(ctx, organizationID, projectID, branchID)
	return err
}

// UpdateGithubRepository converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateGithubRepository(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	// ------------- Path parameter "branchID" -------------
	var branchID string

	err = runtime.BindStyledParameterWithOptions("simple", "branchID", ctx.Param("branchID"), &branchID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter branchID: %s", err))
	}

	ctx.Set(XataScopes, []string{"project:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateGithubRepository(ctx, organizationID, projectID, branchID)
	return err
}

// BranchMetrics converts echo context to params.
func (w *ServerInterfaceWrapper) BranchMetrics(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	// ------------- Path parameter "branchID" -------------
	var branchID string

	err = runtime.BindStyledParameterWithOptions("simple", "branchID", ctx.Param("branchID"), &branchID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter branchID: %s", err))
	}

	ctx.Set(XataScopes, []string{"metrics:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.BranchMetrics(ctx, organizationID, projectID, branchID)
	return err
}

// GetBranchPostgresConfig converts echo context to params.
func (w *ServerInterfaceWrapper) GetBranchPostgresConfig(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	// ------------- Path parameter "branchID" -------------
	var branchID string

	err = runtime.BindStyledParameterWithOptions("simple", "branchID", ctx.Param("branchID"), &branchID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter branchID: %s", err))
	}

	ctx.Set(XataScopes, []string{"branch:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBranchPostgresConfig(ctx, organizationID, projectID, branchID)
	return err
}

// RestoreFromBackup converts echo context to params.
func (w *ServerInterfaceWrapper) RestoreFromBackup(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	// ------------- Path parameter "projectID" -------------
	var projectID string

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", ctx.Param("projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectID: %s", err))
	}

	// ------------- Path parameter "branchID" -------------
	var branchID string

	err = runtime.BindStyledParameterWithOptions("simple", "branchID", ctx.Param("branchID"), &branchID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter branchID: %s", err))
	}

	ctx.Set(XataScopes, []string{"branch:write"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RestoreFromBackup(ctx, organizationID, projectID, branchID)
	return err
}

// ListRegions converts echo context to params.
func (w *ServerInterfaceWrapper) ListRegions(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationID

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", ctx.Param("organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationID: %s", err))
	}

	ctx.Set(XataScopes, []string{"project:read"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListRegions(ctx, organizationID)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/organizations/:organizationID/extensions", wrapper.ListExtensions)
	router.GET(baseURL+"/organizations/:organizationID/githubapp/installations", wrapper.ListGithubAppInstallations)
	router.POST(baseURL+"/organizations/:organizationID/githubapp/installations", wrapper.CreateGithubAppInstallation)
	router.PUT(baseURL+"/organizations/:organizationID/githubapp/installations/:githubInstallationID", wrapper.UpdateGithubAppInstallation)
	router.GET(baseURL+"/organizations/:organizationID/images", wrapper.ListImages)
	router.GET(baseURL+"/organizations/:organizationID/instanceTypes", wrapper.ListInstanceTypes)
	router.GET(baseURL+"/organizations/:organizationID/projects", wrapper.ListProjects)
	router.POST(baseURL+"/organizations/:organizationID/projects", wrapper.CreateProject)
	router.GET(baseURL+"/organizations/:organizationID/projects/limits", wrapper.GetDefaultProjectLimits)
	router.DELETE(baseURL+"/organizations/:organizationID/projects/:projectID", wrapper.DeleteProject)
	router.GET(baseURL+"/organizations/:organizationID/projects/:projectID", wrapper.GetProject)
	router.PATCH(baseURL+"/organizations/:organizationID/projects/:projectID", wrapper.UpdateProject)
	router.GET(baseURL+"/organizations/:organizationID/projects/:projectID/backups", wrapper.ListBackups)
	router.GET(baseURL+"/organizations/:organizationID/projects/:projectID/backups/:backupID", wrapper.GetBackup)
	router.GET(baseURL+"/organizations/:organizationID/projects/:projectID/branches", wrapper.ListBranches)
	router.POST(baseURL+"/organizations/:organizationID/projects/:projectID/branches", wrapper.CreateBranch)
	router.DELETE(baseURL+"/organizations/:organizationID/projects/:projectID/branches/:branchID", wrapper.DeleteBranch)
	router.GET(baseURL+"/organizations/:organizationID/projects/:projectID/branches/:branchID", wrapper.DescribeBranch)
	router.PATCH(baseURL+"/organizations/:organizationID/projects/:projectID/branches/:branchID", wrapper.UpdateBranch)
	router.GET(baseURL+"/organizations/:organizationID/projects/:projectID/branches/:branchID/credentials", wrapper.GetBranchCredentials)
	router.DELETE(baseURL+"/organizations/:organizationID/projects/:projectID/branches/:branchID/githubapp/repository", wrapper.DeleteGithubRepository)
	router.GET(baseURL+"/organizations/:organizationID/projects/:projectID/branches/:branchID/githubapp/repository", wrapper.GetGithubRepository)
	router.POST(baseURL+"/organizations/:organizationID/projects/:projectID/branches/:branchID/githubapp/repository", wrapper.CreateGithubRepository)
	router.PUT(baseURL+"/organizations/:organizationID/projects/:projectID/branches/:branchID/githubapp/repository", wrapper.UpdateGithubRepository)
	router.POST(baseURL+"/organizations/:organizationID/projects/:projectID/branches/:branchID/metrics", wrapper.BranchMetrics)
	router.GET(baseURL+"/organizations/:organizationID/projects/:projectID/branches/:branchID/postgres-config", wrapper.GetBranchPostgresConfig)
	router.POST(baseURL+"/organizations/:organizationID/projects/:projectID/branches/:branchID/restore", wrapper.RestoreFromBackup)
	router.GET(baseURL+"/organizations/:organizationID/regions", wrapper.ListRegions)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9W3Pcttn/V8Hw3wu7pQ52ks6/upMtxdGM46iS3KZ19HqwJHYXNRdgAVDS1tX72d/B",
	"kSAJkNzV6hTvTSJzSRyf54fnjK9JRhclJYgInhx8TRjiJSUcqX8cVmJOGf4PFJiSY8Yok08zSgQiQv4J",
	"y7LAmfp571+cEvmMZ3O0gPKvktESMYF1YziX/80Rzxgu5RfJQaLaBDhHROApRgxMKQOCwewLJjMASQ5y",
	"NKlmM0xmSZqIZYmSg4QLJv99myYLxDmcoW67P1ULSHYYgjmcFAgg1Y15G6CbsoCYyB7EHAFYibnsX08D",
	"UKaeuGkDzHmFur3fpglD/64wQ3ly8MkN5dK9SCf/QplIbuWboVnblQbXc0QGRzGFuOByzu8QQQxnv9fd",
	"2PxqmwUz3bpVl3NbUC7M84ySHMsv1CKfMuQe/AhxgfLf63qX3kwVkVXsAYi91a2c9hwB2QXiAmAOCBVg",
	"gYTqWS+pWsU3MPtSlW8pmeJZxaDuoj39IyQkswA4oZVQDU8YJNlc7rHApKIVBxPVkHzitZS29ky/dIEX",
	"gTUWeIEAnYIcLveuEfqiJ3aNAGQICKh3EEyrojB9ydahEIjJr//nxW+//fG/n/Z3/nz58uDF/qf9nb9c",
	"/veV/t/rT/s738nHn/Z3frhUz17+IbT/DElCxJScIoapoa8prAqRHLxub8OcXoOCykExJIf5BaHS0oAe",
	"IAeQ0YrkcjuSNJlStoAiOUgwEd+9TtJkAW/wolokB9/9kCYLTPQ/XruBYSLQDDG1ZU2qSJObHXSTFVUu",
	"yUewCskn8n1GYKGf3KZmc39GAuZQwO6SL8wvZmNhdz+7O6g2/uQosH+OLE6OfBqBnNMMQ4FycI3F3Fuf",
	"0BY02mx34f1LUkp/SwiyAiMuzhAXlKHwgM1LoKSYCIAJUFQIryAuFKdPNacJytzWqln525lDgXbkd6FR",
	"hFCqIvjfFerAVO9sCiiG5qJfua+ptAAL50laE0Nz37ogliZv1KtvGVLAYAAljjS2Kw0CmfpM8T9B1/W4",
	"cyy/XWAChT5KFrCUPKhOlYoLukgOkv+3V8tjewb59vRwfmR08bYFWJjMEcNi+MNTyOSpdes4ZPkBSlxL",
	"FjRH8jEl6JdpcvDpa/IHhqYrNDj2g+bQby/DaNvB9t7GA58MceUv6g9YAJ89HUVrECgrVlKOgJYLJMpy",
	"8GIBb8AP+yCbQwYzgRh/qUHxPSIzMU8OfthvIPwnuPOfw51/Svj+U/33Drj8YxDM1TZ0BnsxR0D+AiqO",
	"ciAo8GgIgQkS1wgRIBvjEmL08BHfTdIEEQnPnxyFpJbGLgO9E7gYliPkS26lGpTdaY9nsEAX9J+I0aE9",
	"PK9fbW1ki4fVGM1C9fKsAioY4lfvRzURmGWIc82qejKpXGmmZirlrxJyfk1Z3jlY3A+dPk7NL60OPOqS",
	"Z9gE8iAA29677X6041qj3dZKuk7Seh6XoUO7e0RHuLkj7marsPHbouICsQ4fW56wpBwl4LZ4Kr9LW2OI",
	"k4yHZp15tIdguSnERKVqIyRsnEylwMsREam/Yde4KIBpUQvjqgVPXK3Hr9UBKReNnL0bTXzi7zEXcXHr",
	"57a4ZYaloEgddAXm6pyzsCOPcSnaU0NAIXznx0SCSYBx/j5HYo4aOIxNkwzN5BKIORSAV2VJmbAiH6/X",
	"Y0JpgaCiHHUEo/xQBCAVLxAXcFHqOfjbATkwH44WmFY/aqwkGD1pxsplH+NyWRSXx+N8Y5jJatRej8i0",
	"0qRrLB/KreUAghwxfIVyB79EakxUEsI1VlAmH8hhWcWhO5BqUuDsUCHiKKqCRUGvOdDfGShVwr4i84Yd",
	"Jkhcmhq7Xb1DdMZgOceZJdjrOZLaYIOgc1QWdKlIrIv+Zb4e2RaQC2C+voOEbA6Fmnv8IbmJt5Y8bXN2",
	"HHDiYKMlaZSDRRh1UoCJVCAl3GDBARdQVFyB4hgdfhNS5YPi1yaOz4wSgjL5r3O9591VNxIDqF8Fmj46",
	"UgbmNRYMsuQWfrfw+wzhdyNaS5pobBpEGTWkc/3uM8J+M7sAvLRha+icaC5476nBcBYgrkOQ0aIwuEWn",
	"8uyQL4IXWVmlYIEWlC1TqTJ/SXd3d18qBkUwm1u+wIQLSDKtO8Oa2ZonCCKK+8cBkh6CfL9LXYhZX4BA",
	"i0H60LM+1x/VJlXIGFwaKmNi/MAqgkXYviB/sSuihw9elIhliAg4QymYLAXiKVjwFCCR7b4cJCc9slQt",
	"nFsRN38zlMHtPtPOgK5KBmczhmZQ+2o6M5I6jdpO7y0gKJghpXtp3JvTazVdKWjsKAukRiBMDF0IxK5g",
	"oWzltiGU74JjRTwEac1thghiUCAAAUclVH/K5d/RMwWmNev62E3SeuetPgmvZtqKlCibelCvbO+8IciW",
	"m4XkwOz9SFOvJf74GtpXwMmRWsN/V4gt/VkMDrVmh45uKelMHXVew07RLytFOZKBteH0SwNw+GeYCXyF",
	"Wg9xXqgjC4lryr58xmTGNPDYJ8g+wLTkn+WJa/++ZljIbwsoEMmW9jf7T/uzmDNazeZlJewb3hP70jUs",
	"PvMlyT6bpWfIuQk/F3CmH4c22rF0c7HO5eNVNnccP9YEkDZ5Ks6a53PKeiwGbyDHWVyCV4YDTGpfoKBG",
	"4NvTJw2QbG4GkXYNSlthdivMboXZ37UtoQd6nFAdMRwYiwAmesDKZNo0XEKSK9tBRXLEiqWEgtxhhtah",
	"O7BjQfItrUhoJamABSDVYqIJ1LVXi5ZGCqg7cH50343+Kk0EFpIykw+utZ5G2j73Gs7PEMyXkeF+6Buo",
	"sk5IiUcy71KtlsNjWMQGvt8/cN3WCsPnQ/EcSoDHJMdXOK8kHrZn0u1tlLx9Yj6vNTI7r7Y4FN8OJ/cU",
	"eIqyZVagkbab9+79dlxPyVCmONFAVi/aRmJ8soopzHSqm53ZebVYQLa00Grm470XkFCCXHhumS+XYEfb",
	"x4cERsqU8U5Q8PbD6TtvEG8bo2uNJT6IC/W4w5DLUp03zcbcyWMFzPOLw4uP558v/nF6/Pnjh/PT47cn",
	"P54cHyVp45efjg/fX/z0j9bTi7PDD+cnxx8uWs9/PPz4vv3sp5M3x2cfDi+Oj5LLgFimV9mbT9oCnCBb",
	"+8wSB8yPCmwHQxcU12eQgAmyoK/FJQLQTcO/kzySw/4Duu7z1Uf98gar7uSVn+MJYgQKFFK4lBWjc4Ty",
	"Oa2KXC6n+zhXRgj9Op4CLABBKFcq1UTBrVRmlIYZlBHwIhjld0q5mDF0/tf3QL0hm6t47aHvQnyfGhhm",
	"J7n2Dlflt2vLhbKlRgBBjzSoJ8YbZHIKGVwgub3KBpDr0EFYnDZIsl+mTg7ZBAsmEc9bvKabtXT9uJF2",
	"oKhmtZKhgsL8PZ4waK07YV3a6xDdCES4MkzIQ7awH8sNNA2upGQb/ZKPOu/ty7IzZX4DgvZG+33fOuw7",
	"J/fGrKaUBen8jeEr/bs8e9/hN+DFDM+gMk297B3+6x/2R0Qo3qbJW5yzYyLYMhDMgHMWCCY5OToDk4Jm",
	"X8ALtDvbTcFvyau/vN599ef/v7u/u7/3+vvfkpfr63kFnKDC0aDqDKnhDUnfarShcyHoJ+pOq8EOuTkm",
	"1JHQEZeVD8sPn+nKz4+HXReehVdjV0MKkd3cQAGb7/A6BHELTZuAptXVW0tbysY6Qb1K7hjoc4iH/XN6",
	"FxxfIbYE2RwXuadSG31VB/8S6r7eBRdz+XNDUtq9I3I+LOQ1VHTFl54a3uAlb2F7gOS9r+QMaSonHb3c",
	"10ycvqQEd6T9MYPKeTmHPLB6VqFQP/t2/bqXklHjkwqQFOQhkj1Tz2vOC488BYiXKMOwKJYS0aaVxnBC",
	"tZq21K9Flaue6XjKeL1KPsO8UB2kLv441WSq/rKeG6sAqVeteUY77+zL6s8Zg7n5m3wh9Fp7JgIaW1vd",
	"rhckZIdW9nG9bUHCUsz3Dot5NTksS6WSF4WadNQdhL2XTgKmzXdY/FRNwGFZAv9VoOLAfSb68/fJMNs0",
	"OxuawxkqKceCsmV0+LPWiyEjqJkCcy+tN/hAV6EJHNszIK40Kva0Z2F9aHQYtFfScf342l1QXqIh5+8R",
	"zaoFIkLv5sez9+N1kbpnY6TsnvP6rDtzq9duAnN7HtbB/xYa3HoAxfgiqNSJoMwijPnCpzOPaxsrXVQz",
	"THRAdFWEHUpXiPGBtbevDEmVZqWaW1V/rPaou26m1cs1M4I0F/kwEAoCiHF4O5UHyg2ZQWJSKrsuppUc",
	"PY2u1nH3jPPD+KEKtjeGMh2THpaI7w0M06Sxfl3dxfsVqLQqFQDn9TNBBSUzrnXOO7osOhuwIcdFaw1b",
	"k455NEJI2j4EQsRrcoBcLgcEXbSXojgEv0plJRZcvRrt2k7XIdv7PLBWZAo7jTg/2OXqKqD6B0eltinM",
	"27ARlBEpFVpGDzHZyZEdoHxP75tRMGQ3OpFH9Vov0N3Zwd/TDXFCYKvrJW2twip8cXL6Iy4Ekh2vZIyQ",
	"B+zJKZjaj4FUis1G2hyELmcY480oJ1BtBArG3QxE/jbGhjlALtCtff63Vrt+MWq8OQkbUsISmdXumisx",
	"rYribzGJQGUquwaiUoFUM/9FWbQZ9euodsKimZpmVCyLmRNaNgR76jjDD26adRwpLDA50X+/Goy7imSj",
	"+auRNpY4uItNJ2Pcj9ZxYpN+n6fRcmHckb1S1EenA89fZ+cATGKwQoUA8uIFDB15J9pHKKl02torzK1a",
	"XSxNcQLVCHihQqtehkbjx2T4DXmfB+XvmCczpm3XzsTAIMIuTP/FDm1BNkPidL1Fko3rBtwK5RUzFQcg",
	"LuiVPCPtBCKLZfV1zAG/xiKb25oTNp6m28swkKljwzk2vc8a0/VMCeduxRSFxzz4HUZqRMeG02Z1iKGL",
	"Oo0GkYY/915wybcu4FMtkRfq6aloYwI67TyDAU9HY8jnChZVK5a4OT9hBYTxEcKqTc+qq6NaOltct2w/",
	"CQFdL3Z682+EHiZuYqEmfe1Cr1zt161duZ93/vfg8k8ezbc+a09c6p0UlngnozmaIbKDbgSDOwLO1Dpe",
	"wQLnyiyX1DCpJnTacAUM+NlV4GMb08ca+qPOlbLheGj7Exhctqz70V6UepwHRjo2eKa5GM4hMkgJ3gxC",
	"Wx5rdpVVhoBjMivQiIXookSWoVJIqeEMkpD4FbZq158BJr+T26AJ2xywmPd0KpHkb46/I9HtRUGvUQ7k",
	"u7bpF3gKTEWiSYFerhanDW/+Ztm/FamtvQquR9VZoK+unIhJrEntFFm1yZDT1ogLkY4uPDu97oROW6vf",
	"dAqFvbWqpE5PF+YN00Vwh3tbPacVyyJtc/WbPRIaPXmHjpW3PT/O55bhbaT7uRVQ1go2vp5Dl6hu1i+j",
	"RDBa8IjhtjbRvsfkS4igyRd5tHrM2fhq5HKGlQm5gH4AstdJb2sMZXSxQCSHAz765ouBsYIXtUCLFqVY",
	"vgz3p0L049ZmK7dBP45DfQMwbxugG/1ncwVAggIBvyCAplOtuwcEYh0yHyFD/eOelElnlC3b3fTb9UTU",
	"P6/yBKzRu0FYHnW7kxqr4LdpQaH8v/KE2tfSJK/TzuysLkcatYX2eTZt2w2+DzJsC35C9N6hpXqdg+dd",
	"zFzVVPONyaOZEX1ylCpiT3VStCldZDMrnNQWzKwYH8BnRtjNNV7J/mhncH9mc6vI1taqu+cv9LS1mqnO",
	"n/7DRNsPl0IJbuxKwUFmVp1MfRNkBv6DGAUcCYHJrEuFuHQ2wcFI7Zj5cLVgNDPj0fWHhpJVTXvv8QIL",
	"HoofMGd5oV6wpQu4YFDlH8pFNEvokhGHPFbKzjcuskeHWdUc0or85eb48MyoPdKjUa0OjQDX7oa3I+JT",
	"U0TOGNuMd28Bb97Y7qJyZ51b4arMWLmxRMznSTOong9bH3ScDwt4c1QPwtb1io3MBRyDQr3pxuXtpC9A",
	"8cQvm/hDd8SmmQbGB13jzSGfxDMnumsRyPvwl9OJwaHElG5rjYwI2BGi/XFi0jdOoxH0jtOJOcMD7TQ3",
	"fqDalNzDU8bW7HOStjs7MjM85cWtDbPSme62Ua202QzAJBnQpu3YW2TRWv0InaeJ412fMXuQLoqcvYlz",
	"bYeNSjmy55O2s+kjI6fXxJ0b6uwkVFWKrDgK5CJw5IPJulHIKhzw7g21NqYxunYnoRU2lTOjVqVubS6V",
	"WOHn2OpSui7FVlWhUY3ugpNpywJiCu6WjF7hHOX9RcrMMRYqUrZ7jzkiGymJ80ApthtMjb23SorrxuSM",
	"5/qu81ZOplEwbix7D7pem1Jmr+9V6pEq4waLpa6c/DMmlbDnkimg/N1+O4L1yHELAQv9BYBTFak8x9m8",
	"npQNXK7zfwCeqtnp/GB/VLFYvXr4scGGYEPnfD3v+El/Ds8yflJPYJw+dQqZwLBowbHR2Rtq1TNRmALl",
	"4DGZUu2S0qLOqVVyDk9PvBjCg+TV7v7uvooyKxGBJU4Oku/UI5XBN1ez3vP1Ib73lTa8O7d7dQJDsESK",
	"qfWii0sLhtGV8nq6qtNe/oOUGpVAVCtHrrCzx+ohPU0egzMkQjqg6lMChyqeaUz5frfWcKGiyKdYYsfC",
	"5ADIx343SoU04ugMXyEpHzqvr2RlJbMe1yuSNjxGn0bHWTU6lRLFHGVf2rk1eg1xgcXSVJDHslG5c9Y+",
	"cZDQtjOu5i994NTXJ/RRYsund3ubhuNI5GJqcL5GesGRvxpqgLb2jBlhnRgRG1jHGtPd5ZlZqFaXajx2",
	"OyP913W2oh1eps1bWl7v79/hYoo+jnFOxJpDDE/Y2vhYqbq2uZHewjrCfMg/6A1uzF0TVkfz05gaFeWV",
	"Xz3GT3I03+u1DI3erfle4woW9dGr4Y8Cd+ncpskPv/4aMmeimxJlUnBwLzrBZPhlbcyvGBZLxeU3qljP",
	"J8l8B6pq0aUkIa5z/1UylghDoCNXFcExk5jh0Fvuxyh5se6nRiLwS13o5zYdBHV98MKy3PPlh6C9g8i9",
	"jYgs3Ca2j8XqihFlHok3GLotokbudj9dcA6KapsB6ocF4M1i0sA2O1iK7ctYIArkF4yKXXH9rAJK0cH+",
	"zmHHCLBB6FFr08uuLZK2MFR/k1yavNxguX8VQ6fv4YgpMjZwuit59fNvT7Lac2VgpWO9oflyJd7tNcQM",
	"Z/TdNlnMHBstNHm1sRGFeL7LtP7vLieYV0p/n1ZFsXwMrv1+/y+r9/fQEoaugtjic00GMRaM87UnpNSf",
	"NvamliTAC583dnhGS5S/vIN8sfd11qGVk6PbqNgBLXRksYkq+2gVWmKl8fNG1Z0BvOoCUo/15xkCUjp6",
	"jGahwilygRGHdnUlje+esHKE9W4UVu4/JlbaGlKPj5Xfr9PfcwVYTTv3DLATZTgdAaixuIQRFjhjX7hX",
	"c5vXR1zg86xrQdXtxHpLN2pTU7YJ35b2yKBb27JiAwxJ6U/CsBUjwnsyaukEvUH1UQ9qFb3RDK5ryNra",
	"rtq2qzr6qGOtamCd5t0VrVB+hZw1sa1Zaep+Ma7b1x2wrjH1b8iN0IG/UYONId+KEuZmzWlxyg0BYpN6",
	"BoGx2d+cVqxYngWrGZUMZ0iFcMm36pD11sr69FjHxNKqUZfNZqhFk4kbbUaTiuEidNfwgrKlrrzVEyd2",
	"51TkQBEoVfPrZ0rEfHgNF/I14yh+90YXvtU1w9zCrrKMV1kZyomt4+iu3p5+5MOecrPUujm9wqlPFY3r",
	"ZDrzXTufUNP3SmdrpPbf9oyNn7GNJRtx1tr31e6seObagOih49beRFmnPpDZUDT1ykdqu72e81TYRCnv",
	"CgCUq7tlwRxye1GAoGG3kFvKTR21ahpu/FNGF8/ZPRSnCneU2ShTDQGNE8zeTzI6t9UE4Azmsnqe0UEA",
	"OnSUFaKqbwl1Bt1DPuvF4GaM/8dl3Qxx7y5wIUomNllATGw2totMrwOYlbCiw2J5zE90WodxbUZ41hZ1",
	"P6IaPx+X0T1koK13hXk0p2tUyOwDu64cEnXxxNaz8s2uLrXuG0GQPs8TbO92v9DiAEC7dhZy61YQV/aK",
	"SBKYlVraNgI/uZu1EsVGJIaNEGVG99ALjX5yn6k3XOfWpFb50CmoNq/IZKV0gfEdEkd6RM3UuU1BpK5c",
	"o/minunzEnxGwIFZtQAoHK2w302RY53D+p233K0eRzMcsJNZgde+mr+ca7ZAIaX5FLEFJDoVX7/DfY+t",
	"S0tammxqS8N+jJc75T02aIgBVjiw5cKhvoYug4RQoRItSU4J6vLCkRrRRoUEI7dYeKmx70k6ce36C2p2",
	"JzxQt9d3NKd9Hy8J2ThC9VjyZ+PBfDLnriboRv5CEALGGdH9UuaKz2TruuBZiINPjkaciHlvzaA4Lgzr",
	"D6GTbsvakrXNjt4zc+8/pMRtiyDYqT3T0IenovL7UoRZ2qjSD0U2j8dSaYnXq5sS5+lU7tkcQK7r5djS",
	"FZIsY2FWW35Wd/aotdg4Nz+4UaEnZ2/8jWZ9toQ17Ab7j2Y3sOVotti1otBjorBG4ldX+1nPOeJrQHs6",
	"4X7QYbKABM48J4kpIMBXcoqYbwLBBabVsHfjjRniVhSSC+qv4lMSi0J1HAJk1aYFTzr29mKMn0WThbtd",
	"fsjdYke0mrelZ5hbtFvDOdOCj80kChqA2CAc7n3VfwTD95vIONMVylozG4WL+lWtgK4Ciu+QwcQtJN4r",
	"JI4flNnJrmQXGIulrCejtLaBtIuHF/UUFx7ebuFvTUXVZ/xNQuBGEDBaYm9ECE0nKtUHsZWCZ9otBaHR",
	"dy81gzVS40YyriUdPmOLSUbETO9GmG8YVNUmuNWPh/48CSkzSqsusMcU4tpAXI+mD0kp42XOeM22eIxh",
	"iPK3MmccdPV69ccDeWVKLdjW9fRGxgO5+nZxPNoFb1pFHW0qsOQjwDMGhSRGBnLE8JV97mdxllCVnzeX",
	"DkeCg964+x2+YaDyIprsdczkiVgWh2Hkram3bSs2PnBkkB7E+Zwy0Sf32Xuln0iQ0Ho5mq9eD390ylBG",
	"ib6I/Ufl5XtMKBsOTKrrP4bQzBML9QauGZUUEgv3vuq/7hY9YRi2N3hCEuV6YRFbeGyN2pHLY6jGeqsH",
	"4jQsUW0+TCOEYdsojfUwyAVp9OPP5mI0apzYYIhGG3x8LVLfRZdKBiL64g2gyS21Bfib1Yvb8CPHNdkC",
	"0NMEIGcv9C6iuFc42t+wwDZCVtuGl2xSgXyHrCoWcM42Ncjh4JJm0d5miEkXk6IRJqlfbzwFClNN9Cws",
	"CppFsEmPZItMTxKZ+uJi1sei+1JeNSmtpLruPwXVdRunsp7YZ8JUxgFhR/ncoE/CUz73MoYUQ0F934WR",
	"DLuOUmtucS93sO9h4WqTOLMptOhCFkdMxaq5xGRvue1lIbrKeaSIRWVaSB5XYvI3PoAS3s/OeWvIfCtA",
	"jcYOjzaCUtSZ89ObO2Aa3BhAkU3iRF2ssb7Poc9ydWSsVV6lQO8iiHjx15jFXrfXvp/id11gsVcSfBih",
	"6qGtTGddEjFGpi18bCIvKMqJ8VKFfaXevXYEBb9CYU1atlk+WOd9U/jwDoktOPyOwOEu8QyWpkeVWfXo",
	"pR13YNsZE3YQp2Er6H/DBUXeIRFg8vri041UmB8Eo/5a8lvceK64cb/l87uXoT1K5fwGTHXQJyA3bavn",
	"b7COyRpy06oF59eAr/CdfVv4+tbhq/8ux0cpZr8yfD3rgvZPLTNyDfgKVqj39umezNELJBjOdLlBI/o1",
	"Mc95cNVrWyP0w7qszLo/EpQ09z6AI+YnU5nXwPUWNLqgYdhslJl54XitY2JO7Ypv2NgsWX/GEN/Rvn7P",
	"MbVGyJJyu1RMxYOf6obP//q+FUZQw0iDePyYJveKLsHbiB/gqUqOKYUqd8ggmekXdCGwK1hU8t8q9MmM",
	"RD8LJyWqrs1QuS6LsA01eKpBUFGSej5RUU1SawQktMKRY3PdhkttOlxqaKnv3+PHEBeUocFqmvItZatX",
	"OThe4vaobCCTwjkiKagDlWd6gD8yutjmcbdGbSLZHhMrG0NoZng/fRXa0NY2r+hbCc4K5AU1EU1FmhIq",
	"5oj1xe2vnHJuKE13ZthjBIyb8r5rXYhkvtV11VFZ0OV93Ntge9F3stTLWmd16r51/NPKd3ifmQXY7LVI",
	"5h6Zx70PabPe0CilBC4gcnu22s1DpnDIMZGN5N2e/j5Hmm9MgRHIEED6Zc8LKAnDOC2UEODfomNgf0Jp",
	"gaCqDofzEBS0N9tSVruh+uafxiYG2vylc8EIvVZxC254KcBTwJHwOgKYA0qKpbe0gupvWlZ2UhX6UiJD",
	"Mp3xldWkwNmhgvj4ysojApQFJOqqI/3NzhRmSh6gamQag5AYXtz2PT950hpG2t7xzjKufJmQpdJVUvwt",
	"tX7b9wcNOd473D1cGM/cv+bbeG/dRx0GqW8q9a/WS8fkqA2cOTXUuoF2BdBW/67EXvfGENOJ7dQ37mQm",
	"kTxtalv+cP3huPN+/HAG7pXmdeOeJf728vb/AgAA///osg01KuwAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
