apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: keycloak-eg
  namespace: {{ .Release.Namespace }}
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  gatewayClassName: eg
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: {{ .Values.gateway.envoyProxy.name }}
  listeners:
    - name: {{ if .Values.gateway.tlsSecret }}https{{ else }}http{{ end }}
      protocol: {{ if .Values.gateway.tlsSecret }}HTTPS{{ else }}HTTP{{ end }}
      port: {{ if .Values.gateway.tlsSecret }}443{{ else }}80{{ end }}
      hostname: {{ .Values.gateway.hostname | default "localhost" | quote }}
      {{- with .Values.gateway.tlsSecret }}
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ . | quote }}
      {{- end }}
