apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: keycloak-eg
  namespace: {{ .Release.Namespace }}
  labels:
    xata.tech/gateway: auth
spec:
  parentRefs:
    - name: keycloak-eg
  hostnames:
    - {{ .Values.gateway.hostname | default "localhost" | quote }}
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: auth-keycloak-service
          port: 8080
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /realms/
        - path:
            type: PathPrefix
            value: /resources/
        - path:
            type: PathPrefix
            value: /robots.txt
        - path:
            type: PathPrefix
            value: /.well-known/oauth-authorization-server
      timeouts:
        request: 60s
