apiVersion: k8s.keycloak.org/v2beta1
kind: Keycloak
metadata:
  name: auth-keycloak
  namespace: {{ .Release.Namespace }}
  {{- if .Values.retainOnUninstall }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  instances: {{ .Values.instances }}
  image: "{{ .Values.image.repository }}{{ if .Values.image.digest }}@{{ .Values.image.digest }}{{ else }}:{{ .Values.image.tag }}{{ end }}"
  update:
    strategy: {{ .Values.update.strategy }}
    {{- with .Values.tolerations }}
    scheduling:
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  db:
    vendor: {{ .Values.db.vendor }}
    {{- if .Values.db.host }}
    host: {{ .Values.db.host }}
    {{- end }}
    {{- if .Values.db.database }}
    database: {{ .Values.db.database }}
    {{- end }}
    {{- with .Values.db.usernameSecret }}
    {{- if and .name .key }}
    usernameSecret:
      name: {{ .name }}
      key: {{ .key }}
    {{- end }}
    {{- end }}
  {{- with .Values.db.passwordSecret }}
  {{- if and .name .key }}
  env:
    - name: KCRAW_DB_PASSWORD
      secret:
        name: {{ .name }}
        key: {{ .key }}
  {{- end }}
  {{- end }}
  http:
    httpEnabled: {{ .Values.http.httpEnabled }}
    httpPort: {{ .Values.http.httpPort }}
  hostname:
    strict: {{ .Values.hostname.strict }}
    admin: {{ .Values.hostname.admin | quote }}
    {{- if .Values.hostname.hostname }}
    hostname: {{ .Values.hostname.hostname | quote }}
    {{- end }}
  features:
    enabled:
      {{- toYaml .Values.features.enabled | nindent 6 }}
  resources:
    {{- toYaml .Values.resources | nindent 4 }}
  proxy:
    headers: {{ .Values.proxy.headers }} # double check your reverse proxy sets and overwrites the X-Forwarded-* headers
  {{- with .Values.additionalOptions }}
  additionalOptions:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.tracing.enabled }}
  tracing:
    {{- toYaml .Values.tracing | nindent 4 }}
  {{- end }}
  {{- with .Values.tolerations }}
  scheduling:
    tolerations:
      {{- toYaml . | nindent 6 }}
  {{- end }}
  {{- with .Values.unsupported }}
  unsupported:
    {{- toYaml . | nindent 4 }}
  {{- end }}
