apiVersion: v1
kind: ConfigMap
metadata:
  name: branch-operator-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: branch-operator
data:
  XATA_IMAGE_SECRETS: {{ .Values.config.branchOperator.imageSecrets | quote }}
  XATA_CLUSTERS_TOLERATIONS: {{ .Values.config.branchOperator.clustersTolerations | quote }}
  XATA_CLOUD_PROVIDER: {{ .Values.config.branchOperator.cloudProvider | quote }}
  {{- with .Values.config.branchOperator.backupsAwsRoleArn }}
  XATA_BACKUPS_AWS_ROLE_ARN: {{ . | quote }}
  {{- end }}
  XATA_BARMAN_REGION_SECRET_NAME: {{ .Values.config.branchOperator.barmanRegionSecret.name | quote }}
  XATA_BARMAN_REGION_SECRET_KEY: {{ .Values.config.branchOperator.barmanRegionSecret.key | quote }}
  XATA_XATASTOR_ENABLED: {{ .Values.config.branchOperator.xatastor.enabled | quote }}
  XATA_BRANCH_MAX_CONCURRENT: {{ .Values.config.branchOperator.branchMaxConcurrent | quote }}
  XATA_WAKEUP_MAX_CONCURRENT: {{ .Values.config.branchOperator.wakeupMaxConcurrent | quote }}
  {{- with .Values.extraConfig }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
