apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  # Shared by the API and Keycloak Envoy Gateways.
  name: eg-custom-proxy-config
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        {{- toYaml .Values.envoyService | nindent 8 }}
      envoyDeployment:
        replicas: {{ .Values.proxyReplicas | default 1 }}
        patch:
          type: StrategicMerge
          value:
            spec:
              template:
                spec:
                  containers:
                    - name: shutdown-manager
                      resources:
                        limits:
                          cpu: 200m
                          memory: 100Mi
