{{- if .Values.tls.gateway.generate }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace .Values.tls.gateway.existingSecret }}
{{- $cert := genSelfSignedCert (first .Values.tls.gateway.dnsNames) nil .Values.tls.gateway.dnsNames 365 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.gateway.existingSecret }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
type: kubernetes.io/tls
data:
  tls.crt: {{ if $existing }}{{ index $existing.data "tls.crt" }}{{ else }}{{ $cert.Cert | b64enc }}{{ end }}
  tls.key: {{ if $existing }}{{ index $existing.data "tls.key" }}{{ else }}{{ $cert.Key | b64enc }}{{ end }}
{{- end }}
