// Code generated by mockery v3.0.0-alpha.0. DO NOT EDIT.

package mocks

import (
	postgresversions "xata/internal/postgresversions"

	mock "github.com/stretchr/testify/mock"
)

// ImageProvider is an autogenerated mock type for the ImageProvider type
type ImageProvider struct {
	mock.Mock
}

type ImageProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *ImageProvider) EXPECT() *ImageProvider_Expecter {
	return &ImageProvider_Expecter{mock: &_m.Mock}
}

// BuildImageURL provides a mock function with given fields: imageName
func (_m *ImageProvider) BuildImageURL(imageName string) string {
	ret := _m.Called(imageName)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(imageName)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ImageProvider_BuildImageURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildImageURL'
type ImageProvider_BuildImageURL_Call struct {
	*mock.Call
}

// BuildImageURL is a helper method to define mock.On call
//   - imageName string
func (_e *ImageProvider_Expecter) BuildImageURL(imageName interface{}) *ImageProvider_BuildImageURL_Call {
	return &ImageProvider_BuildImageURL_Call{Call: _e.mock.On("BuildImageURL", imageName)}
}

func (_c *ImageProvider_BuildImageURL_Call) Run(run func(imageName string)) *ImageProvider_BuildImageURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ImageProvider_BuildImageURL_Call) Return(_a0 string) *ImageProvider_BuildImageURL_Call {
	_c.Call.Return(_a0)
	return _c
}

// ExtractVersionFromImageName provides a mock function with given fields: imageName
func (_m *ImageProvider) ExtractVersionFromImageName(imageName string) string {
	ret := _m.Called(imageName)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(imageName)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ImageProvider_ExtractVersionFromImageName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractVersionFromImageName'
type ImageProvider_ExtractVersionFromImageName_Call struct {
	*mock.Call
}

// ExtractVersionFromImageName is a helper method to define mock.On call
//   - imageName string
func (_e *ImageProvider_Expecter) ExtractVersionFromImageName(imageName interface{}) *ImageProvider_ExtractVersionFromImageName_Call {
	return &ImageProvider_ExtractVersionFromImageName_Call{Call: _e.mock.On("ExtractVersionFromImageName", imageName)}
}

func (_c *ImageProvider_ExtractVersionFromImageName_Call) Run(run func(imageName string)) *ImageProvider_ExtractVersionFromImageName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ImageProvider_ExtractVersionFromImageName_Call) Return(_a0 string) *ImageProvider_ExtractVersionFromImageName_Call {
	_c.Call.Return(_a0)
	return _c
}

// GetAllImageNames provides a mock function with given fields:
func (_m *ImageProvider) GetAllImageNames() []string {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// ImageProvider_GetAllImageNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllImageNames'
type ImageProvider_GetAllImageNames_Call struct {
	*mock.Call
}

// GetAllImageNames is a helper method to define mock.On call
func (_e *ImageProvider_Expecter) GetAllImageNames() *ImageProvider_GetAllImageNames_Call {
	return &ImageProvider_GetAllImageNames_Call{Call: _e.mock.On("GetAllImageNames")}
}

func (_c *ImageProvider_GetAllImageNames_Call) Run(run func()) *ImageProvider_GetAllImageNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ImageProvider_GetAllImageNames_Call) Return(_a0 []string) *ImageProvider_GetAllImageNames_Call {
	_c.Call.Return(_a0)
	return _c
}

// GetAllVersions provides a mock function with given fields:
func (_m *ImageProvider) GetAllVersions() []string {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// ImageProvider_GetAllVersions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllVersions'
type ImageProvider_GetAllVersions_Call struct {
	*mock.Call
}

// GetAllVersions is a helper method to define mock.On call
func (_e *ImageProvider_Expecter) GetAllVersions() *ImageProvider_GetAllVersions_Call {
	return &ImageProvider_GetAllVersions_Call{Call: _e.mock.On("GetAllVersions")}
}

func (_c *ImageProvider_GetAllVersions_Call) Run(run func()) *ImageProvider_GetAllVersions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ImageProvider_GetAllVersions_Call) Return(_a0 []string) *ImageProvider_GetAllVersions_Call {
	_c.Call.Return(_a0)
	return _c
}

// GetMajorForVersion provides a mock function with given fields: version
func (_m *ImageProvider) GetMajorForVersion(version string) string {
	ret := _m.Called(version)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(version)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ImageProvider_GetMajorForVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMajorForVersion'
type ImageProvider_GetMajorForVersion_Call struct {
	*mock.Call
}

// GetMajorForVersion is a helper method to define mock.On call
//   - version string
func (_e *ImageProvider_Expecter) GetMajorForVersion(version interface{}) *ImageProvider_GetMajorForVersion_Call {
	return &ImageProvider_GetMajorForVersion_Call{Call: _e.mock.On("GetMajorForVersion", version)}
}

func (_c *ImageProvider_GetMajorForVersion_Call) Run(run func(version string)) *ImageProvider_GetMajorForVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ImageProvider_GetMajorForVersion_Call) Return(_a0 string) *ImageProvider_GetMajorForVersion_Call {
	_c.Call.Return(_a0)
	return _c
}

// GetVersionsForMajor provides a mock function with given fields: major
func (_m *ImageProvider) GetVersionsForMajor(major string) []string {
	ret := _m.Called(major)

	var r0 []string
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(major)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// ImageProvider_GetVersionsForMajor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVersionsForMajor'
type ImageProvider_GetVersionsForMajor_Call struct {
	*mock.Call
}

// GetVersionsForMajor is a helper method to define mock.On call
//   - major string
func (_e *ImageProvider_Expecter) GetVersionsForMajor(major interface{}) *ImageProvider_GetVersionsForMajor_Call {
	return &ImageProvider_GetVersionsForMajor_Call{Call: _e.mock.On("GetVersionsForMajor", major)}
}

func (_c *ImageProvider_GetVersionsForMajor_Call) Run(run func(major string)) *ImageProvider_GetVersionsForMajor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ImageProvider_GetVersionsForMajor_Call) Return(_a0 []string) *ImageProvider_GetVersionsForMajor_Call {
	_c.Call.Return(_a0)
	return _c
}

// ParseImageVersion provides a mock function with given fields: image
func (_m *ImageProvider) ParseImageVersion(image string) (*postgresversions.ImageVersion, error) {
	ret := _m.Called(image)

	var r0 *postgresversions.ImageVersion
	if rf, ok := ret.Get(0).(func(string) *postgresversions.ImageVersion); ok {
		r0 = rf(image)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*postgresversions.ImageVersion)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(image)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ImageProvider_ParseImageVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseImageVersion'
type ImageProvider_ParseImageVersion_Call struct {
	*mock.Call
}

// ParseImageVersion is a helper method to define mock.On call
//   - image string
func (_e *ImageProvider_Expecter) ParseImageVersion(image interface{}) *ImageProvider_ParseImageVersion_Call {
	return &ImageProvider_ParseImageVersion_Call{Call: _e.mock.On("ParseImageVersion", image)}
}

func (_c *ImageProvider_ParseImageVersion_Call) Run(run func(image string)) *ImageProvider_ParseImageVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ImageProvider_ParseImageVersion_Call) Return(_a0 *postgresversions.ImageVersion, _a1 error) *ImageProvider_ParseImageVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// ValidateImage provides a mock function with given fields: image
func (_m *ImageProvider) ValidateImage(image string) error {
	ret := _m.Called(image)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(image)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ImageProvider_ValidateImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateImage'
type ImageProvider_ValidateImage_Call struct {
	*mock.Call
}

// ValidateImage is a helper method to define mock.On call
//   - image string
func (_e *ImageProvider_Expecter) ValidateImage(image interface{}) *ImageProvider_ValidateImage_Call {
	return &ImageProvider_ValidateImage_Call{Call: _e.mock.On("ValidateImage", image)}
}

func (_c *ImageProvider_ValidateImage_Call) Run(run func(image string)) *ImageProvider_ValidateImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ImageProvider_ValidateImage_Call) Return(_a0 error) *ImageProvider_ValidateImage_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewImageProvider interface {
	mock.TestingT
	Cleanup(func())
}

// NewImageProvider creates a new instance of ImageProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewImageProvider(t mockConstructorTestingTNewImageProvider) *ImageProvider {
	mock := &ImageProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
