image:
  repository: ghcr.io/xataio/xata/clusters
  digest: ""
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

service:
  grpcPort: 5002
  type: ClusterIP
  loadBalancerClass: ""
  annotations: {}

config:
  clusters:
    clustersNamespace: xata-clusters
    storageClass: ""
    nodeSelector: ""
    volumeSnapshotClass: ""
    cloudProvider: aws
    xatastor: { enabled: false }
    useStorageQoSClasses: false
    pgbackrest:
      encryptionEnabled: false
  observability:
    victoriaMetricsURL: "http://victoria-metrics.xata-observability.svc.cluster.local:8428"
    victoriaLogsURL: "http://victoria-logs.xata-observability.svc.cluster.local:9428"

resources:
  limits:
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 200Mi

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - clusters
          topologyKey: kubernetes.io/hostname

tolerations:
  - key: "kubernetes.io/arch"
    operator: "Equal"
    value: "arm64"
    effect: "NoSchedule"

replicaCount: 1
strategy: {}

extraConfig: {}

extraEnvFrom: []
